Hands on with Numpy in Python

In [2]:
#First we need to load dependencies
import numpy as np

## Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [39]:
a = np.array([1, 2, 3])  # Create a rank 1 array

print("a shape")
print (a.shape )           # Prints "(3,)"

b = np.array([[1,2,3]])   # Create a rank 2 array
print("b shape")
print (b.shape)                     # Prints "(2, 3)"


a shape
(3,)
b shape
(1, 3)


## Array math
1. Matrix multiplication
2. Element wise multiplication

In [53]:
print(b.shape)
print(b)
c=a[:,None]
print(c.shape)
print(c)
a[:,None].dot(b)


(1, 3)
[[1 2 3]]
(3, 1)
[[1]
 [2]
 [3]]


array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])